"""initial schema — all MVP tables

ponytail: hand-written, not autogenerated via `alembic revision
--autogenerate`, because there was no live Postgres available to run
that command against at the time this was written. It should match the
current models exactly, but treat it as unverified until you've run
`alembic upgrade head` against a real dev DB and it succeeds cleanly.
If anything's off, `alembic revision --autogenerate -m "fix"` against a
running DB with this migration applied will catch the diff.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-20
"""

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- auth: users, workspaces, membership (no FK dependencies outside this group) ---
    op.create_table(
        "users",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("phone", sa.String(32), nullable=True, unique=True),
        sa.Column("password_hash", sa.String, nullable=False),
        sa.Column("totp_secret", sa.String, nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "workspaces",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("jurisdiction_code", sa.String(8), nullable=False, server_default="pk"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "workspace_members",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("user_id", sa.String(26), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("workspace_id", sa.String(26), sa.ForeignKey("workspaces.id"), nullable=False),
        sa.Column("role", sa.String, nullable=False, server_default="viewer"),
        sa.UniqueConstraint("user_id", "workspace_id"),
    )
    op.create_index("ix_workspace_members_user_id", "workspace_members", ["user_id"])
    op.create_index("ix_workspace_members_workspace_id", "workspace_members", ["workspace_id"])

    # --- accounting_core: accounts before journal_entries/lines (FK target) ---
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("code", sa.String, nullable=False),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("type", sa.String, nullable=False),
        sa.Column("parent_id", sa.String(26), sa.ForeignKey("accounts.id"), nullable=True),
    )
    op.create_index("ix_accounts_tenant_id", "accounts", ["tenant_id"])

    op.create_table(
        "journal_entries",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("entry_date", sa.Date, nullable=False),
        sa.Column("memo", sa.String, nullable=True),
        sa.Column("status", sa.String, nullable=False, server_default="draft"),
        sa.Column("source", sa.String, nullable=False, server_default="manual"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_journal_entries_tenant_id", "journal_entries", ["tenant_id"])

    op.create_table(
        "journal_lines",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("journal_entry_id", sa.String(26), sa.ForeignKey("journal_entries.id"), nullable=False),
        sa.Column("account_id", sa.String(26), sa.ForeignKey("accounts.id"), nullable=False),
        sa.Column("debit", sa.Numeric(18, 2), nullable=False, server_default="0"),
        sa.Column("credit", sa.Numeric(18, 2), nullable=False, server_default="0"),
    )
    op.create_index("ix_journal_lines_journal_entry_id", "journal_lines", ["journal_entry_id"])
    op.create_index("ix_journal_lines_account_id", "journal_lines", ["account_id"])

    op.create_table(
        "accounting_periods",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("start_date", sa.Date, nullable=False),
        sa.Column("end_date", sa.Date, nullable=False),
        sa.Column("is_closed", sa.Boolean, nullable=False, server_default=sa.false()),
    )
    op.create_index("ix_accounting_periods_tenant_id", "accounting_periods", ["tenant_id"])

    # --- audit (core, cross-cutting) ---
    op.create_table(
        "audit_log_entries",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("actor_user_id", sa.String(26), nullable=False),
        sa.Column("entity_type", sa.String, nullable=False),
        sa.Column("entity_id", sa.String, nullable=False),
        sa.Column("action", sa.String, nullable=False),
        sa.Column("diff_json", sa.String, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_audit_log_entries_tenant_id", "audit_log_entries", ["tenant_id"])
    op.create_index("ix_audit_log_entries_actor_user_id", "audit_log_entries", ["actor_user_id"])
    op.create_index("ix_audit_log_entries_entity_type", "audit_log_entries", ["entity_type"])
    op.create_index("ix_audit_log_entries_entity_id", "audit_log_entries", ["entity_id"])

    # --- sales: customers before invoices, invoices before invoice_lines ---
    op.create_table(
        "customers",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("email", sa.String, nullable=True),
        sa.Column("phone", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_customers_tenant_id", "customers", ["tenant_id"])

    op.create_table(
        "invoices",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("customer_id", sa.String(26), sa.ForeignKey("customers.id"), nullable=False),
        sa.Column("invoice_number", sa.String, nullable=False),
        sa.Column("issue_date", sa.Date, nullable=False),
        sa.Column("due_date", sa.Date, nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="draft"),
        sa.Column("currency", sa.String, nullable=False, server_default="PKR"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_invoices_tenant_id", "invoices", ["tenant_id"])
    op.create_index("ix_invoices_customer_id", "invoices", ["customer_id"])

    # --- tax: tax_rates before invoice_lines (FK target) ---
    op.create_table(
        "tax_rates",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("rate_percent", sa.Float, nullable=False),
        sa.Column("is_default", sa.Boolean, nullable=False, server_default=sa.false()),
    )
    op.create_index("ix_tax_rates_tenant_id", "tax_rates", ["tenant_id"])

    op.create_table(
        "fbr_filings",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("period_start", sa.String, nullable=False),
        sa.Column("period_end", sa.String, nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="draft"),
    )
    op.create_index("ix_fbr_filings_tenant_id", "fbr_filings", ["tenant_id"])

    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("invoice_id", sa.String(26), sa.ForeignKey("invoices.id"), nullable=False),
        sa.Column("description", sa.String, nullable=False),
        sa.Column("quantity", sa.Numeric(18, 2), nullable=False, server_default="1"),
        sa.Column("unit_price", sa.Numeric(18, 2), nullable=False),
        sa.Column("tax_rate_id", sa.String(26), sa.ForeignKey("tax_rates.id"), nullable=True),
    )
    op.create_index("ix_invoice_lines_invoice_id", "invoice_lines", ["invoice_id"])

    # --- purchases: vendors before bills ---
    op.create_table(
        "vendors",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("email", sa.String, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_vendors_tenant_id", "vendors", ["tenant_id"])

    op.create_table(
        "bills",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("vendor_id", sa.String(26), sa.ForeignKey("vendors.id"), nullable=False),
        sa.Column("bill_date", sa.Date, nullable=False),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("receipt_file_id", sa.String, nullable=True),
        sa.Column("is_paid", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_bills_tenant_id", "bills", ["tenant_id"])
    op.create_index("ix_bills_vendor_id", "bills", ["vendor_id"])

    # --- banking: bank_accounts (FKs accounts) before bank_transactions ---
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("account_number_last4", sa.String, nullable=True),
        sa.Column("ledger_account_id", sa.String(26), sa.ForeignKey("accounts.id"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_bank_accounts_tenant_id", "bank_accounts", ["tenant_id"])

    op.create_table(
        "bank_transactions",
        sa.Column("id", sa.String(26), primary_key=True),
        sa.Column("tenant_id", sa.String(26), nullable=False),
        sa.Column("bank_account_id", sa.String(26), nullable=False),
        sa.Column("txn_date", sa.Date, nullable=False),
        sa.Column("description", sa.String, nullable=False),
        sa.Column("amount", sa.Numeric(18, 2), nullable=False),
        sa.Column("suggested_account_id", sa.String(26), nullable=True),
        sa.Column("category_status", sa.String, nullable=False, server_default="needs_review"),
        sa.Column("confidence", sa.Float, nullable=True),
        sa.Column("journal_entry_id", sa.String(26), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_bank_transactions_tenant_id", "bank_transactions", ["tenant_id"])


def downgrade() -> None:
    # Drop in reverse dependency order.
    op.drop_table("bank_transactions")
    op.drop_table("bank_accounts")
    op.drop_table("bills")
    op.drop_table("vendors")
    op.drop_table("invoice_lines")
    op.drop_table("fbr_filings")
    op.drop_table("tax_rates")
    op.drop_table("invoices")
    op.drop_table("customers")
    op.drop_table("audit_log_entries")
    op.drop_table("accounting_periods")
    op.drop_table("journal_lines")
    op.drop_table("journal_entries")
    op.drop_table("accounts")
    op.drop_table("workspace_members")
    op.drop_table("workspaces")
    op.drop_table("users")